server:
  port: 2222
  servlet:
    context-path: /
name:
  kjw
age:
  18
spring:
  datasource:
    driver-class-name:
      com.mysql.cj.jdbc.Driver
    url:
      jdbc:mysql://192.168.222.21:3306/security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username:
      root
    password:
      root
    druid:
      driver-class-name:
        com.mysql.cj.jdbc.Driver
      url:
        jdbc:mysql://192.168.222.21:3306/security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username:
        root
      password:
        root
mybatis:
  mapper-locations:
    classpath:mapper/*.xml